# Site settings
title: BiLibre
email: bilibre@kolyvan.com
description:
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://bilibre.github.io" # the base hostname & protocol for your site
twitter_username: kolyvan
github_username:  kolyvan

# Build settings
markdown: kramdown
